name: Build Container Check

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t auto-register-spark-ui-k8s:latest .

      - name: Run Docker image and check for error
        id: docker_run
        run: |
          set -o pipefail
          docker run --rm auto-register-spark-ui-k8s:latest 2>&1 | tee output.log
          if grep -q "unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST" output.log; then
            echo "Error found: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST"
            exit 1
          fi